/*
 * MAIN Generated Driver File
 * 
 * @file main.c
 * 
 * @defgroup main MAIN
 * 
 * @brief This is the generated driver implementation file for the MAIN driver.
 *
 * @version MAIN Driver Version 1.0.2
 *
 * @version Package Version: 3.1.2
*/

/*
© [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS “AS IS.” 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP’S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include "mcc_generated_files/system/system.h"

/* Keep duty values in the full 10-bit PWM range used by MCC PWM drivers. */
#define PWM_DUTY_FULL_SCALE   (1023U)
#define PWM_PERCENT(p)        ((uint16_t)(((uint32_t)(p) * PWM_DUTY_FULL_SCALE) / 100U))

int main(void)
{
    /* One-time peripheral setup generated by MCC. */
    SYSTEM_Initialize();

    /* Simple controller tuning values for first demo. */
    const int16_t deadband = 15;
    const uint16_t baseDuty = PWM_PERCENT(45);
    const uint16_t minDuty = PWM_PERCENT(20);
    const uint16_t maxDuty = PWM_PERCENT(70);
    const uint16_t directionForward = PWM_DUTY_FULL_SCALE;
    const uint16_t directionReverse = 0U;
    const uint16_t lostWireThreshold = 20U;
    const uint8_t lostWireLimit = 5U;
    const uint8_t speedReduceShift = 1U; /* divide |error| by 2 for speed reduction */

    adc_result_t left_adc;
    adc_result_t right_adc;
    int16_t left_filt;
    int16_t right_filt;
    int16_t error;
    uint16_t motorDuty;
    uint16_t directionDuty = directionForward;
    uint8_t lostWireCount = 0U;

    /* Prime filter state from first sample so startup is smooth. */
    left_adc = ADC_ChannelSelectAndConvert(ADC_CHANNEL_ANA0);
    right_adc = ADC_ChannelSelectAndConvert(ADC_CHANNEL_ANC2);
    if (left_adc < 0)
    {
        left_adc = 0;
    }
    if (right_adc < 0)
    {
        right_adc = 0;
    }
    left_filt = left_adc;
    right_filt = right_adc;

    while (1)
    {
        /* 1) Read both sensors each loop. */
        left_adc = ADC_ChannelSelectAndConvert(ADC_CHANNEL_ANA0);
        right_adc = ADC_ChannelSelectAndConvert(ADC_CHANNEL_ANC2);
        if (left_adc < 0)
        {
            left_adc = 0;
        }
        if (right_adc < 0)
        {
            right_adc = 0;
        }

        /* 2) Tiny IIR filter: filtered += (new - filtered) >> 3 */
        left_filt += (left_adc - left_filt) >> 3;
        right_filt += (right_adc - right_filt) >> 3;

        /* 3) Signed tracking error. */
        error = right_filt - left_filt;

        /* 7) Lost-wire fail-safe: both sensors very low for several cycles. */
        if ((left_filt < (int16_t)lostWireThreshold) && (right_filt < (int16_t)lostWireThreshold))
        {
            if (lostWireCount < lostWireLimit)
            {
                lostWireCount++;
            }
        }
        else
        {
            lostWireCount = 0U;
        }

        if (lostWireCount >= lostWireLimit)
        {
            /* Fail-safe: slow down and default forward. */
            motorDuty = minDuty;
            directionDuty = directionForward;
        }
        else
        {
            int16_t absError;
            int16_t speedReduction;

            /* 5) Direction output on PWM6 as digital-like 0/100%. */
            if (error > deadband)
            {
                directionDuty = directionForward;
            }
            else if (error < -deadband)
            {
                directionDuty = directionReverse;
            }
            /* inside deadband: keep last directionDuty */

            /* 6) Base speed reduced by |error| with clamping. */
            absError = (error >= 0) ? error : -error;
            speedReduction = absError >> speedReduceShift;

            if (speedReduction >= (int16_t)baseDuty)
            {
                motorDuty = minDuty;
            }
            else
            {
                int16_t rawDuty = (int16_t)baseDuty - speedReduction;

                if (rawDuty < (int16_t)minDuty)
                {
                    motorDuty = minDuty;
                }
                else if (rawDuty > (int16_t)maxDuty)
                {
                    motorDuty = maxDuty;
                }
                else
                {
                    motorDuty = (uint16_t)rawDuty;
                }
            }
        }

        PWM5_LoadDutyValue(motorDuty);
        PWM6_LoadDutyValue(directionDuty);

        /* 8) Fixed controller rate (~10 ms). */
        __delay_ms(10);
    }
}
